package com.example.doesitfly.model

data class FlyingSiteBean(
    val acces: String,
    val alt: String,
    val balise: String,
    val conditions_ideales: String,
    val cp: String,
    val dangers: String,
    val date_modification: String,
    val description: String,
    val handi: String,
    val id: String,
    val lat: String,
    val lon: String,
    val nom: String,
    val numero: String,
    val numero_cross: String,
    val pratiques: String,
    val reg_aerienne: String,
    val restrictions: String,
    val signaletique: String,
    val site_sous_type: String,
    val site_type: String,
    val sous_nom: String,
    val suid: String,
    val trajet_attero_deco: String,
    val trajet_parcking: String,
    val vent_defavo: String,
    val vent_favo: String,
    val ville: String,
    val webcam: String
)